
spring: 
  profile: test

spring:
  application:
    name: springcloud-config-client-3355
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-8001
    prefer-ip-address: true     #访问路径可以显示IP地址
server:
  port: 3355